name: Typescript Playwright UI Testing Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  Typescript-Playwright-UI-Test-Execution:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: npx playwright install-deps chromium

      - name: Test using Playwright
        run: npm run run_test

      - name: Upload Playwright report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Playwright-report-results
          path: report-results/results.html
  